/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.rtr;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Pcm quadro = new Pcm();

        Scanner entrada = new Scanner(System.in);

        quadro.openFile(entrada);
        quadro.findPaq();

    }
}
